In [1]:
import numpy as np

In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def nonlin_sin(x, deriv=False):
    if(deriv==True):
        return  np.cos(x)
    return np.sin(x)

In [3]:
# input dataset
X = np.array([  [0,0,1], [0,1,1], [1,0,1], [1,1,1] ])

In [4]:
# output dataset            
y = np.array([[0,0,1,1]]).T

In [5]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# TASK1

In [6]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [7]:
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l1_error))))


    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)


print("==================================")
print("Final weights:")
print("...............")
print("syn0", syn0)
print("==================================")
print("Output After Training:")
print(l1) 



Error:0.5172082754380926
Error:0.026070259693142646
Error:0.0181554678525527
Error:0.014723482568835052
Error:0.012699314779145614
Error:0.011327232073339398
Error:0.010319216334688502
Error:0.009538603095349355
Error:0.00891115763147092
Error:0.008392641900637663
Final weights:
...............
syn0 [[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


# TASK2

Combination 1 (1 hidden layer with 4 nodes)

In [8]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for iter in range(10000):

    # forward propagation
    
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss?
    l2_error = y - l2
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l2
    l2_delta = l2_error * nonlin(l2,True)

    # update weights
    syn1 += np.dot(l1.T,l2_delta)
    
    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("==================================")
print("Final weights:")
print(".............")
print("syn0", syn0)
print(".............")
print("syn1", syn1)

print("==================================")
print("Output After Training:") 
print(l2)


Error:0.49494493792434335
Error:0.013408533801299933
Error:0.00895740999912654
Error:0.007121378424557574
Error:0.006065139119176284
Error:0.005360653699904899
Error:0.004849162688197633
Error:0.00445668349700743
Error:0.004143563721909778
Error:0.0038864213873892692
Final weights:
.............
syn0 [[ 3.08070015 -2.76230281 -3.07542102 -3.17685335]
 [-0.15900668 -0.00321099 -0.14587323  0.17220606]
 [-0.57216678  0.46120314  0.86476672  0.66545104]]
.............
syn1 [[ 7.12899529]
 [-3.80286758]
 [-3.93336204]
 [-4.70594607]]
Output After Training:
[[0.00355272]
 [0.00261954]
 [0.99594753]
 [0.99554204]]


Combination 2 (1 hidden layer with 10 nodes)

In [9]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,10)) - 1
syn1 = 2*np.random.random((10,1)) - 1

for iter in range(10000):

    # forward propagation
    
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss?
    l2_error = y - l2
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l2
    l2_delta = l2_error * nonlin(l2,True)

    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("==================================")
print("Final weights:")
print("...............")
print("syn0", syn0)
print("...............")
print("syn1", syn1)
print("==================================")
print("Output After Training:") 
print(l2)

Error:0.5006594163755165
Error:0.015352952743999589
Error:0.010261265457251647
Error:0.008154625865804482
Error:0.006941738572463338
Error:0.00613256724140381
Error:0.005545040461284668
Error:0.005094236981565303
Error:0.004734618359208907
Error:0.004439323384156331
Final weights:
...............
syn0 [[-3.05063215 -0.32802776  3.30055907 -2.0080543   0.80797206  3.00398001
   0.37179042 -1.16042978 -3.18398177 -1.00348753]
 [ 0.23955595 -1.01049934 -0.17710757  0.61093931  0.11084229  0.42615085
  -0.46195135  0.24866754  0.42531019 -0.96350972]
 [ 0.9939253   0.888814   -1.14659707  0.02658285  0.43413383 -1.33075834
  -0.21257486  0.77712793  0.92625837 -0.19507627]]
...............
syn1 [[-3.43425603]
 [-0.60665354]
 [ 4.12045708]
 [-2.07966793]
 [ 0.84366897]
 [ 3.5835207 ]
 [ 0.16629678]
 [-0.85113695]
 [-3.71802915]
 [-1.02807107]]
Output After Training:
[[0.00462541]
 [0.00353349]
 [0.99589293]
 [0.99549958]]


Combination 3 (2 hidden layers with 5 nodes each)

In [10]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,5)) - 1
syn1 = 2*np.random.random((5,5)) - 1
syn2 = 2*np.random.random((5,1)) - 1

for iter in range(10000):

    # forward propagation
    
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l3 = nonlin(np.dot(l2,syn2))

    # how much did we miss?
    l3_error = y - l3
#     l2_error = y - l2
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l3_error))))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l3
    l3_delta = l3_error * nonlin(l3,True)
    
    # how much did we miss?
    l2_error = l3_delta.dot(syn2.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l2_delta = l2_error * nonlin(l2,True)
    
    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn2 += l2.T.dot(l3_delta)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("===================================")    
print("Final weights:")
print("...............")
print("syn0", syn0)
print("...............")
print("syn1", syn1)
print("...............")
print("syn2", syn2)
print("===================================")
print("Output After Training:") 
print(l3)

Error:0.5021886092147305
Error:0.017857520115654828
Error:0.01168948604784428
Error:0.009230333071297555
Error:0.007834146513813579
Error:0.006909544184107535
Error:0.006241244741794055
Error:0.005730024086298623
Error:0.0053230910205401905
Error:0.004989480485020193
Final weights:
...............
syn0 [[ 2.45662204 -3.46926643 -1.73599422  3.18183438  0.51685548]
 [-0.62275846 -0.06214086  0.36887632  0.09262319  0.83155839]
 [-0.65647583  1.61354994  0.22836027 -1.49465638  0.31180797]]
...............
syn1 [[ 0.2724724  -1.97214756  1.14355619  0.36352712  0.97477212]
 [-0.25546829  4.15072737 -1.83672065 -0.57694809 -0.87212594]
 [-0.76414424  2.17508954 -1.25860092  0.50724624  0.05756671]
 [ 0.89163227 -2.89649668  1.61113282  0.8021093   0.80048797]
 [-0.04692245 -0.41983081  0.18533441  0.29465282 -0.7832579 ]]
...............
syn2 [[ 1.12752936]
 [-7.74566803]
 [ 3.47047843]
 [ 1.15996669]
 [ 1.38758041]]
Output After Training:
[[0.00540802]
 [0.00426475]
 [0.9957749 ]
 [0.995

# TASK3

In [11]:
# input dataset
X_multi = np.array([  [0,0,1], [0,1,1], [1,0,1], [1,1,1] ])

# output dataset            
y_multi = np.array([[0,0,1,1], [1,1,1,1]]).T

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1

for iter in range(10000):

    # forward propagation
    
    l0 = X_multi
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss?
    l2_error = y_multi - l2
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l2
    l2_delta = l2_error * nonlin(l2,True)

    # update weights
    syn1 += np.dot(l1.T,l2_delta)
    
    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("=======================================")
print("Final weights:")
print("...............")
print("syn0", syn0)
print("...............")
print("syn1", syn1)
print("=======================================")
print("Output After Training:") 
print(l2)


Error:0.5411477835858883
Error:0.010551776874028414
Error:0.007177781474590511
Error:0.005755250879584643
Error:0.004927703107813263
Error:0.004371714593283085
Error:0.003965893571828556
Error:0.0036532136702658907
Error:0.0034029257955859164
Error:0.003196811273004541
Final weights:
...............
syn0 [[ 2.40141935  1.18644133 -4.98520096  0.90959043]
 [-0.08945486  0.9257672   0.31511728 -0.44646629]
 [-0.1764787   0.30131743  2.12091204  0.93681901]]
...............
syn1 [[  4.04609781   3.90595003]
 [  1.77155187   2.29585708]
 [-10.07219318   1.19450976]
 [  1.08033551   2.29972395]]
Output After Training:
[[0.00470598 0.99703961]
 [0.00420999 0.99751458]
 [0.99587381 0.99941802]
 [0.99541778 0.99946445]]


# TASK4

Combination 1 (1 hidden layer with 4 nodes) with sin non-linearity 

In [12]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for iter in range(10000):

    # forward propagation
    
    l0 = X
    l1 = nonlin_sin(np.dot(l0,syn0))
    l2 = nonlin_sin(np.dot(l1,syn1))

    # how much did we miss?
    l2_error = y - l2
    
    if((iter%1000) == 0):
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l2
    l2_delta = l2_error * nonlin_sin(l2,True)

    # update weights
    syn1 += np.dot(l1.T,l2_delta)
    
    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin_sin(l1,True)

    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

print("=======================================")
print("Final weights:")
print("................")
print("syn0:", syn0)
print("................")
print("syn1:", syn1)
print("=======================================")
print("Output After Training:") 
print(l2)


Error:0.2650332677245139
Error:0.8001189572995078
Error:1.1949894748419179
Error:0.3692465248271469
Error:0.5157497181446448
Error:0.9312838901661243
Error:1.0360009250527005
Error:0.47121271631507566
Error:0.6345030892974368
Error:0.39623327882955045
Final weights:
................
syn0: [[-2690138.12665678   849724.78819918  -750058.91111648  -586383.51333236]
 [-1337913.74754314   416880.26064032  -374655.51309014  -291722.90768336]
 [-2681380.27049307   838536.81583375  -739564.83919522  -581749.66284461]]
................
syn1: [[-449.4321906 ]
 [ -11.37269047]
 [  45.26027607]
 [-104.43060128]]
Output After Training:
[[-0.84549362]
 [-0.99512683]
 [-0.12291439]
 [ 0.18350695]]
